<?xml version="1.0"?>

<robot name ="differential_drive_robot" xmlns:xacro="https://www.ros/wiki/xacro">

<!-- Body dimensions -->

<xacro:property name="body_link_x_dim" value="1"/>
<xacro:property name="body_link_y_dim" value="0.6"/>
<xacro:property name="body_link_z_dim" value="0.3"/>

<!-- Wheel dimensions -->
<xacro:property name="wheel_link_radius" value="0.15"/>
<xacro:property name="wheel_link_length" value="0.1"/>
<xacro:property name="wheel_link_z_location" value="-0.1"/>

<!-- Material density -->
<xacro:property name="body_density" value="2710"/>
<xacro:property name="wheel_density" value="2710"/>

<!-- Pi constant -->
<xacro:property name="pi_const" value="3.14159265359"/>

<!-- Robot body and wheel mass -->
<xacro:property name="body_mass" value="${body_density*body_link_x_dim*body_link_y_dim*body_link_z_dim}"/>
<xacro:property name="wheel_mass" value="${wheel_density*pi_const*wheel_link_radius*wheel_link_radius*wheel_link_length}"/>

<!-- Robot body inertia -->
<xacro:property name="Iz_wheel" value="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}"/>
<xacro:property name="I_wheel" value="${(1/12)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius + wheel_link_length*wheel_link_length)}"/>
<xacro:macro name="inertial_wheel">
    <inertial>
        <origin rpy ="0 0 0" xyz="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${Iz_wheel}" ixy="0" ixz="0" iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}"/>
    </inertial>
</xacro:macro>

<xacro:include filename="$(find robot_model_pkg)/urdf/robot.gazebo" />
    

<!--We need a dummy link otherwsie Gazebo will complain-->
<link name="dummy">
</link>
<joint name="dummy_joint" type="fixed">
    <parent link="dummy"/>
    <child link="body_link"/>
</joint>

<!-- BODY LINK OF THE ROBOT -->
<link name="body_link">
    <visual>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>
    <collision>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass}"/>
        <inertia
        ixx="${(1/12)*body_mass*(body_link_y_dim*body_link_y_dim + body_link_z_dim*body_link_z_dim)}" 
        ixy="0" 
        ixz="0" 
        iyy="${(1/12)*body_mass*(body_link_x_dim*body_link_x_dim + body_link_z_dim*body_link_z_dim)}" 
        iyz="0" 
        izz="${(1/12)*body_mass*(body_link_x_dim*body_link_x_dim + body_link_y_dim*body_link_y_dim)}"/>
    </inertial>
</link>

<!--Wheel1 BACK RIGHT WHEEL-->
<joint name="wheel1_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel1_link"/>
    <origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1" friction="1.0"/>
</joint>
<link name="wheel1_link">
    <visual>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
        <origin rpy="1.570795 0 0" xyz="0 0 0" />
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
        <origin rpy="1.570795 0 0" xyz="0 0 0" />
    </collision>
    <xacro:inertial_wheel />
</link>


<!--Wheel2 BACK LEFT WHEEL-->
<joint name="wheel2_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel2_link"/>
    <origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1" friction="1.0"/>
</joint>
<link name="wheel2_link">
    <visual>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
    </collision>
    <xacro:inertial_wheel />
</link>

<!--Wheel3 FRONT RIGHT WHEEL-->
<joint name="wheel3_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel3_link"/>
    <origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1" friction="1.0"/>
</joint>
<link name="wheel3_link">
    <visual>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
    </collision>
    <xacro:inertial_wheel />
</link>

<!--Wheel4 FRONT LEFT WHEEL-->
<joint name="wheel4_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel4_link"/>
    <origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1" friction="1.0"/>
</joint>
<link name="wheel4_link">
    <visual>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="1.570795 0 0"/>
    </collision>
    <xacro:inertial_wheel />
</link>
</robot>							
